package com.bestway.common.logcommit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0_02-b08-fcs Generated
 * source version: 2.0
 * 
 */
@WebServiceClient(name = "ServerService", targetNamespace = "http://jbcus.bestway.com/", wsdlLocation = "http://61.145.126.185:9998/Service?wsdl")
public class BswServerService extends Service {

	private final static URL SERVERSERVICE_WSDL_LOCATION;

	static {
		URL url = null;
		try {
			url = new URL("http://61.145.126.185:9998/Service?wsdl");
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		System.out.println("-----------------new URL  ");
		SERVERSERVICE_WSDL_LOCATION = url;
	}

	public BswServerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BswServerService() {
		super(SERVERSERVICE_WSDL_LOCATION, new QName(
				"http://jbcus.bestway.com/", "ServerService"));
		System.out.println("-----------------new BswServerService");
	}

	/**
	 * 
	 * @return returns Server
	 */
	@WebEndpoint(name = "ServerPort")
	public BswServer getServerPort() {
		try {
			return (BswServer) super
					.getPort(new QName("http://jbcus.bestway.com/",
							"ServerPort"), BswServer.class);
		} catch (Exception e) {
			return null;
		}
	}

}
