
package com.bestway.client.upgrade;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-hudson-182-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UpgradeServiceService", targetNamespace = "http://com/bestway/client/upgrade", wsdlLocation = "http://localhost:7070/UpgradeService?wsdl")
public class UpgradeServiceService2
    extends Service
{

//    private final static URL UPGRADESERVICESERVICE_WSDL_LOCATION;
//    private final static Logger logger = Logger.getLogger(com.bestway.client.upgrade.UpgradeServiceService.class.getName());

//    static {
//        URL url = null;
//        try {
//            URL baseUrl;
//            baseUrl = com.bestway.client.upgrade.UpgradeServiceService.class.getResource(".");
//            url = new URL(baseUrl, "http://localhost:7070/UpgradeService?wsdl");
//        } catch (MalformedURLException e) {
//            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7070/UpgradeService?wsdl', retrying as a local file");
//            logger.warning(e.getMessage());
//        }
//        UPGRADESERVICESERVICE_WSDL_LOCATION = url;
//    }

    public UpgradeServiceService2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

//    public UpgradeServiceService() {
//        super(UPGRADESERVICESERVICE_WSDL_LOCATION, new QName("http://com/bestway/client/upgrade", "UpgradeServiceService"));
//    }

    /**
     * 
     * @return
     *     returns UpgradeService
     */
    @WebEndpoint(name = "UpgradeServicePort")
    public UpgradeService getUpgradeServicePort() {
        return super.getPort(new QName("http://com/bestway/client/upgrade", "UpgradeServicePort"), UpgradeService.class);
    }


	public static UpgradeServiceService2 getUpgradeServiceService(String serverHostAddress){
//		="192.168.1.159";
		URL serverUrl=null;
		try {
			serverUrl = new URL("http://"+serverHostAddress+":7070/UpgradeService?wsdl");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			throw new RuntimeException(e.getMessage());
		}
		UpgradeServiceService2 serverService = new UpgradeServiceService2(
				serverUrl, new QName("http://com/bestway/client/upgrade", "UpgradeServiceService"));
		return serverService;
	}

	public static void main(String[] args) {
		UpgradeServiceService2 serverService = getUpgradeServiceService("localhost");//new CspCardServerService();
		UpgradeService service = serverService.getUpgradeServicePort();
		service.startUpgrade();
		service.checkUpgrade();
	}
	

}
