
package com.bestway.client.upgrade;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "UpgradeServiceService", targetNamespace = "http://com/bestway/client/upgrade", wsdlLocation = "http://localhost:7070/UpgradeService?wsdl")
public class UpgradeServiceService
    extends Service
{


    public UpgradeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

        
    
    public static UpgradeServiceService getUpgradeServiceService(String serverHostAddress){
//		="192.168.1.159";
		URL serverUrl=null;
		try {
			serverUrl = new URL("http://"+serverHostAddress+":7070/UpgradeService?wsdl");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			throw new RuntimeException(e.getMessage());
		}
		UpgradeServiceService serverService = new UpgradeServiceService(
				serverUrl, new QName("http://com/bestway/client/upgrade", "UpgradeServiceService"));
		return serverService;
	}
    

    /**
     * 
     * @return
     *     returns UpgradeService
     */
    @WebEndpoint(name = "UpgradeServicePort")
    public UpgradeService getUpgradeServicePort() {
        return (UpgradeService)super.getPort(new QName("http://com/bestway/client/upgrade", "UpgradeServicePort"), UpgradeService.class);
    }

}
