
package com.bestway.client.upgrade;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UpgradeService", targetNamespace = "http://com/bestway/client/upgrade")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface UpgradeService {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean checkUpgrade();

    /**
     * 
     */
    @WebMethod
    public void startUpgrade();

    /**
     * 
     */
    @WebMethod
    public void stopUpgrade();

    /**
     * 
     * @return
     *     returns com.bestway.client.upgrade.UpgradeInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    public UpgradeInfo getUpgradeInfo();

    /**
     * 
     */
    @WebMethod
    public void restartTomcat();

}
