/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DgErrorMessage.java
 *
 * Created on Mar 21, 2009, 11:33:32 AM
 */
package com.bestway.client.custom.common;

import java.awt.FlowLayout;
import java.util.List;
import java.util.Vector;

import com.bestway.client.util.JTableListColumn;
import com.bestway.client.util.JTableListModel;
import com.bestway.client.util.JTableListModelAdapter;
import com.bestway.jptds.contract.client.CheckBoxRenderer;
import com.bestway.ui.winuicontrol.JDialogBase;

/**
 *
 * @author lxr
 */
public class DgCommonErrorMessage extends JDialogBase {

    private JTableListModel jTableListModel = null;
    public List list = null;

    public List getList() {
        return list;
    }

    public void setList(List list) {
        this.list = list;
    }

    /** Creates new form DgErrorMessage */
    public DgCommonErrorMessage() {
        super();
        initComponents();
    }

    public void setVisible(boolean f) {
        if (f) {
            initOther();
            super.setVisible(f);
        }
    }

    private void initOther() {
        FlowLayout dl = new FlowLayout();
        dl.setAlignment(FlowLayout.CENTER);
        jToolBar1.setLayout(dl);
        initTable(list);
    }

    private JTableListModel initTable(List list) {
        jTableListModel = new JTableListModel(jTable1, list,
                new JTableListModelAdapter() {
                    public List InitColumns() {
                        List<JTableListColumn> list = new Vector<JTableListColumn>();
                        list.add(addColumn("错误对象", "title", 85));
                        list.add(addColumn("错误原因", "message", 320)); //
                        list.add(addColumn("检查时间", "checkDate", 100)); //
                        return list;
                    }
                });
        return jTableListModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("数据检查");

        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

//        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bestway/lptds/images/client/save.gif"))); // NOI18N
        jButton1.setText("确定");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-641)/2, (screenSize.height-472)/2, 641, 472);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
