
package com.bestway.client.upgrade.httpconfig;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UpdateHttpConfigService", targetNamespace = "http://com/bestway/client/upgrade/httpconfig")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface UpdateHttpConfigService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void saveHttpConfig(
        @WebParam(name = "arg0", partName = "arg0")
        HttpConfigEntity arg0);

    /**
     * 
     * @return
     *     returns com.bestway.client.upgrade.httpconfig.HttpConfigEntity
     */
    @WebMethod
    @WebResult(partName = "return")
    public HttpConfigEntity getHttpConfig();

}
