
package com.bestway.client.upgrade.httpconfig;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "UpdateHttpConfigServiceService", targetNamespace = "http://com/bestway/client/upgrade/httpconfig", wsdlLocation = "http://localhost:7070/UpdateHttpConfigService?wsdl")
public class UpdateHttpConfigServiceService
    extends Service
{

    
    public UpdateHttpConfigServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

//    public UpdateHttpConfigServiceService() {
//        super(UPDATEHTTPCONFIGSERVICESERVICE_WSDL_LOCATION, new QName("http://com/bestway/client/upgrade/httpconfig", "UpdateHttpConfigServiceService"));
//    }
    
    public static UpdateHttpConfigServiceService getUpdateHttpConfigServiceService(String serverHostAddress){
//		="192.168.1.159";
		URL serverUrl=null;
		try {
			serverUrl = new URL("http://"+serverHostAddress+":7070/UpdateHttpConfigService?wsdl");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			throw new RuntimeException(e.getMessage());
		}
		UpdateHttpConfigServiceService serverService = new UpdateHttpConfigServiceService(
				serverUrl, new QName("http://com/bestway/client/upgrade/httpconfig", "UpdateHttpConfigServiceService"));
		return serverService;
	}
    

    /**
     * 
     * @return
     *     returns UpdateHttpConfigService
     */
    @WebEndpoint(name = "UpdateHttpConfigServicePort")
    public UpdateHttpConfigService getUpdateHttpConfigServicePort() {
        return (UpdateHttpConfigService)super.getPort(new QName("http://com/bestway/client/upgrade/httpconfig", "UpdateHttpConfigServicePort"), UpdateHttpConfigService.class);
    }

}
