
package com.bestway.cspcard.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.bestway.cspcard.entity.ICCardInfo;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CspCardServer", targetNamespace = "http://cspcard.bsw.com.cn/client")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CspCardServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.com.bsw.cspcard.client.IcCardInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    public ICCardInfo sayHello(
        @WebParam(name = "arg0", partName = "arg0")
        ICCardInfo arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.com.bsw.cspcard.client.IcCardInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    public ICCardInfo getICCardInfo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.com.bsw.cspcard.client.IcCardInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    public ICCardInfo getUnitInfo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.com.bsw.cspcard.client.IcCardInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    public ICCardInfo signMsgData(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);
    
    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.com.bsw.cspcard.client.IcCardInfo
     */
    @WebMethod
    @WebResult(partName = "return")
    public ICCardInfo getAllUnitInfo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);
}
