package com.bestway.cspcard.service.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.bestway.cspcard.entity.ICCardInfo;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0_02-b08-fcs Generated
 * source version: 2.0
 * 
 */
@WebServiceClient(name = "CspCardServerService", targetNamespace = "http://cspcard.bsw.com.cn/client", wsdlLocation = "http://localhost:6666/CspCardServer?wsdl")
public class CspCardServerService extends Service {

//	private final static URL CSPCARDSERVERSERVICE_WSDL_LOCATION;

//	static {
//		URL url = null;
//		try {
//			url = new URL("http://192.168.1.82:6666/CspCardServer?wsdl");
//		} catch (MalformedURLException e) {
//			e.printStackTrace();
//		}
//		CSPCARDSERVERSERVICE_WSDL_LOCATION = url;
//	}

	public CspCardServerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

//	public CspCardServerService() {
//		super(CSPCARDSERVERSERVICE_WSDL_LOCATION, new QName(
//				"http://cspcard.bsw.com.cn/client", "CspCardServerService"));
//	}

	/**
	 * 
	 * @return returns CspCardServer
	 */
	@WebEndpoint(name = "CspCardServerPort")
	public CspCardServer getCspCardServerPort() {
		return (CspCardServer) super.getPort(new QName(
				"http://cspcard.bsw.com.cn/client", "CspCardServerPort"),
				CspCardServer.class);
	}
	
	public static CspCardServerService getCspCardServerService(String serverHostAddress){
//		="192.168.1.159";
		URL serverUrl=null;
		try {
			serverUrl = new URL("http://"+serverHostAddress+":6666/CspCardServer?wsdl");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			throw new RuntimeException(e.getMessage());
		}
		CspCardServerService serverService = new CspCardServerService(
				serverUrl, new QName(
						"http://cspcard.bsw.com.cn/client", "CspCardServerService"));
		return serverService;
	}

	public static void main(String[] args) {
//		String serverHostAddress="192.168.1.159";
//		URL serverUrl=null;
//		try {
//			serverUrl = new URL("http://"+serverHostAddress+":6666/CspCardServer?wsdl");
//		} catch (MalformedURLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//			throw new RuntimeException(e.getMessage());
//		}
//		CspCardServerService serverService = new CspCardServerService(
//				serverUrl, new QName(
//						"http://cspcard.bsw.com.cn/client", "CspCardServerService"));
		CspCardServerService serverService = getCspCardServerService("192.168.1.82");//new CspCardServerService();
		CspCardServer service = serverService.getCspCardServerPort();
		ICCardInfo cardInfo = new ICCardInfo();
		cardInfo.setApplier("百思维&<>\"");
		cardInfo = service.sayHello(cardInfo);
		System.out.println(cardInfo.getApplier());
	}
}
